version: '3.3'

services:
  postgres:
    container_name: postgres-zodo
    image: postgres:16-alpine
    volumes:
      - ./data/zodo-backend:/var/lib/postgresql/data  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reactanandhu
      POSTGRES_DB: zodo-backend
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    restart: unless-stopped
